import { CountryCallingCode } from "libphonenumber-js";

export interface Country {
  nativeLabel: string;
  label: string;
  countryCallingCode: CountryCallingCode | string;
}

export const countries: readonly Country[] = [
  { countryCallingCode: "+93", label: "Afghanistan", nativeLabel: "افغانستان" },
  { countryCallingCode: "+355", label: "Albania", nativeLabel: "Shqipëria" },
  { countryCallingCode: "+213", label: "Algeria", nativeLabel: "الجزائر" },
  { countryCallingCode: "+376", label: "Andorra", nativeLabel: "" },
  { countryCallingCode: "+244", label: "Angola", nativeLabel: "" },
  {
    countryCallingCode: "+1 268",
    label: "Antigua and Barbuda",
    nativeLabel: "",
  },
  { countryCallingCode: "+54", label: "Argentina", nativeLabel: "" },
  { countryCallingCode: "+374", label: "Armenia", nativeLabel: "Հայաստան" },
  { countryCallingCode: "+61", label: "Australia", nativeLabel: "" },
  { countryCallingCode: "+43", label: "Austria", nativeLabel: "Österreich" },
  {
    countryCallingCode: "+994",
    label: "Azerbaijan",
    nativeLabel: "Azərbaycan",
  },
  { countryCallingCode: "+1 242", label: "Bahamas", nativeLabel: "" },
  { countryCallingCode: "+973", label: "Bahrain", nativeLabel: "البحرين" },
  { countryCallingCode: "+880", label: "Bangladesh", nativeLabel: "বাংলাদেশ" },
  { countryCallingCode: "+1 246", label: "Barbados", nativeLabel: "" },
  { countryCallingCode: "+375", label: "Belarus", nativeLabel: "Беларусь" },
  { countryCallingCode: "+32", label: "Belgium", nativeLabel: "België" },
  { countryCallingCode: "+501", label: "Belize", nativeLabel: "" },
  { countryCallingCode: "+229", label: "Benin", nativeLabel: "" },
  { countryCallingCode: "+975", label: "Bhutan", nativeLabel: "འབྲུག་ཡུལ" },
  { countryCallingCode: "+591", label: "Bolivia", nativeLabel: "" },
  {
    countryCallingCode: "+387",
    label: "Bosnia and Herzegovina",
    nativeLabel: "Bosna i Hercegovina",
  },
  { countryCallingCode: "+267", label: "Botswana", nativeLabel: "" },
  { countryCallingCode: "+55", label: "Brazil", nativeLabel: "Brasil" },
  {
    countryCallingCode: "+673",
    label: "Brunei",
    nativeLabel: "Negara Brunei Darussalam",
  },
  { countryCallingCode: "+359", label: "Bulgaria", nativeLabel: "България" },
  { countryCallingCode: "+226", label: "Burkina Faso", nativeLabel: "" },
  { countryCallingCode: "+257", label: "Burundi", nativeLabel: "" },
  { countryCallingCode: "+855", label: "Cambodia", nativeLabel: "កម្ពុជា" },
  { countryCallingCode: "+237", label: "Cameroon", nativeLabel: "Cameroun" },
  { countryCallingCode: "+1", label: "Canada", nativeLabel: "" },
  {
    countryCallingCode: "+238",
    label: "Cape Verde",
    nativeLabel: "Cabo Verde",
  },
  {
    countryCallingCode: "+236",
    label: "Central African Republic",
    nativeLabel: "",
  },
  { countryCallingCode: "+235", label: "Chad", nativeLabel: "Tchad" },
  { countryCallingCode: "+56", label: "Chile", nativeLabel: "" },
  { countryCallingCode: "+86", label: "China", nativeLabel: "中国" },
  { countryCallingCode: "+57", label: "Colombia", nativeLabel: "" },
  { countryCallingCode: "+269", label: "Comoros", nativeLabel: "" },
  {
    countryCallingCode: "+242",
    label: "Congo",
    nativeLabel: "République du Congo",
  },
  {
    countryCallingCode: "+243",
    label: "Congo (Democratic Republic of the)",
    nativeLabel: "République démocratique du Congo",
  },
  { countryCallingCode: "+506", label: "Costa Rica", nativeLabel: "" },
  { countryCallingCode: "+385", label: "Croatia", nativeLabel: "Hrvatska" },
  { countryCallingCode: "+53", label: "Cuba", nativeLabel: "" },
  { countryCallingCode: "+357", label: "Cyprus", nativeLabel: "Κύπρος" },
  {
    countryCallingCode: "+420",
    label: "Czech Republic",
    nativeLabel: "Česká republika",
  },
  { countryCallingCode: "+45", label: "Denmark", nativeLabel: "Danmark" },
  { countryCallingCode: "+253", label: "Djibouti", nativeLabel: "Djibouti" },
  { countryCallingCode: "+1 767", label: "Dominica", nativeLabel: "" },
  {
    countryCallingCode: "+1 809",
    label: "Dominican Republic",
    nativeLabel: "República Dominicana",
  },
  { countryCallingCode: "+593", label: "Ecuador", nativeLabel: "" },
  { countryCallingCode: "+20", label: "Egypt", nativeLabel: "مصر" },
  { countryCallingCode: "+503", label: "El Salvador", nativeLabel: "" },
  {
    countryCallingCode: "+240",
    label: "Equatorial Guinea",
    nativeLabel: "Guinea Ecuatorial",
  },
  { countryCallingCode: "+291", label: "Eritrea", nativeLabel: "ኤርትራ" },
  { countryCallingCode: "+372", label: "Estonia", nativeLabel: "Eesti" },
  { countryCallingCode: "+251", label: "Ethiopia", nativeLabel: "ኢትዮጵያ" },
  { countryCallingCode: "+679", label: "Fiji", nativeLabel: "Fiji" },
  { countryCallingCode: "+358", label: "Finland", nativeLabel: "Suomi" },
  { countryCallingCode: "+33", label: "France", nativeLabel: "" },
  { countryCallingCode: "+241", label: "Gabon", nativeLabel: "" },
  { countryCallingCode: "+220", label: "Gambia", nativeLabel: "" },
  { countryCallingCode: "+995", label: "Georgia", nativeLabel: "საქართველო" },
  { countryCallingCode: "+49", label: "Germany", nativeLabel: "Deutschland" },
  { countryCallingCode: "+233", label: "Ghana", nativeLabel: "" },
  { countryCallingCode: "+30", label: "Greece", nativeLabel: "Ελλάδα" },
  { countryCallingCode: "+1 473", label: "Grenada", nativeLabel: "" },
  { countryCallingCode: "+502", label: "Guatemala", nativeLabel: "" },
  { countryCallingCode: "+224", label: "Guinea", nativeLabel: "Guinée" },
  {
    countryCallingCode: "+245",
    label: "Guinea-Bissau",
    nativeLabel: "Guiné-Bissau",
  },
  { countryCallingCode: "+592", label: "Guyana", nativeLabel: "" },
  { countryCallingCode: "+509", label: "Haiti", nativeLabel: "Haïti" },
  { countryCallingCode: "+504", label: "Honduras", nativeLabel: "" },
  { countryCallingCode: "+36", label: "Hungary", nativeLabel: "Magyarország" },
  { countryCallingCode: "+354", label: "Iceland", nativeLabel: "Ísland" },
  { countryCallingCode: "+91", label: "India", nativeLabel: "भारत" },
  { countryCallingCode: "+62", label: "Indonesia", nativeLabel: "Indonesia" },
  { countryCallingCode: "+98", label: "Iran", nativeLabel: "ایران" },
  { countryCallingCode: "+964", label: "Iraq", nativeLabel: "العراق" },
  { countryCallingCode: "+353", label: "Ireland", nativeLabel: "Éire" },
  { countryCallingCode: "+972", label: "Israel", nativeLabel: "ישראל" },
  { countryCallingCode: "+39", label: "Italy", nativeLabel: "Italia" },
  {
    countryCallingCode: "+225",
    label: "Ivory Coast",
    nativeLabel: "Côte d'Ivoire",
  },
  { countryCallingCode: "+1 876", label: "Jamaica", nativeLabel: "" },
  { countryCallingCode: "+81", label: "Japan", nativeLabel: "日本" },
  { countryCallingCode: "+962", label: "Jordan", nativeLabel: "الأردن" },
  { countryCallingCode: "+7", label: "Kazakhstan", nativeLabel: "Қазақстан" },
  { countryCallingCode: "+254", label: "Kenya", nativeLabel: "Kenya" },
  { countryCallingCode: "+686", label: "Kiribati", nativeLabel: "Kiribati" },
  { countryCallingCode: "+965", label: "Kuwait", nativeLabel: "الكويت" },
  {
    countryCallingCode: "+996",
    label: "Kyrgyzstan",
    nativeLabel: "Кыргызстан",
  },
  { countryCallingCode: "+856", label: "Laos", nativeLabel: "ປະເທດລາວ" },
  { countryCallingCode: "+371", label: "Latvia", nativeLabel: "Latvija" },
  { countryCallingCode: "+961", label: "Lebanon", nativeLabel: "لبنان" },
  { countryCallingCode: "+266", label: "Lesotho", nativeLabel: "Lesotho" },
  { countryCallingCode: "+231", label: "Liberia", nativeLabel: "Liberia" },
  { countryCallingCode: "+218", label: "Libya", nativeLabel: "ليبيا" },
  {
    countryCallingCode: "+423",
    label: "Liechtenstein",
    nativeLabel: "Liechtenstein",
  },
  { countryCallingCode: "+370", label: "Lithuania", nativeLabel: "Lietuva" },
  {
    countryCallingCode: "+352",
    label: "Luxembourg",
    nativeLabel: "Luxembourg",
  },
  {
    countryCallingCode: "+389",
    label: "North Macedonia",
    nativeLabel: "Северна Македонија",
  },
  {
    countryCallingCode: "+261",
    label: "Madagascar",
    nativeLabel: "Madagascar",
  },
  { countryCallingCode: "+265", label: "Malawi", nativeLabel: "" },
  { countryCallingCode: "+60", label: "Malaysia", nativeLabel: "" },
  { countryCallingCode: "+960", label: "Maldives", nativeLabel: "" },
  { countryCallingCode: "+223", label: "Mali", nativeLabel: "" },
  { countryCallingCode: "+356", label: "Malta", nativeLabel: "" },
  {
    countryCallingCode: "+692",
    label: "Marshall Islands",
    nativeLabel: "",
  },
  { countryCallingCode: "+222", label: "Mauritania", nativeLabel: "موريتانيا" },
  { countryCallingCode: "+230", label: "Mauritius", nativeLabel: "" },
  { countryCallingCode: "+52", label: "Mexico", nativeLabel: "México" },
  {
    countryCallingCode: "+691",
    label: "Micronesia",
    nativeLabel: "",
  },
  {
    countryCallingCode: "+373",
    label: "Moldova",
    nativeLabel: "Republica Moldova",
  },
  { countryCallingCode: "+377", label: "Monaco", nativeLabel: "" },
  { countryCallingCode: "+976", label: "Mongolia", nativeLabel: "Монгол улс" },
  { countryCallingCode: "+382", label: "Montenegro", nativeLabel: "Црна Гора" },
  { countryCallingCode: "+212", label: "Morocco", nativeLabel: "المغرب" },
  {
    countryCallingCode: "+258",
    label: "Mozambique",
    nativeLabel: "Moçambique",
  },
  { countryCallingCode: "+95", label: "Myanmar", nativeLabel: "မြန်မာ" },
  { countryCallingCode: "+264", label: "Namibia", nativeLabel: "" },
  { countryCallingCode: "+674", label: "Nauru", nativeLabel: "Nauru" },
  { countryCallingCode: "+977", label: "Nepal", nativeLabel: "नेपाल" },
  { countryCallingCode: "+31", label: "Netherlands", nativeLabel: "Nederland" },
  {
    countryCallingCode: "+64",
    label: "New Zealand",
    nativeLabel: "New Zealand",
  },
  { countryCallingCode: "+505", label: "Nicaragua", nativeLabel: "Nicaragua" },
  { countryCallingCode: "+227", label: "Niger", nativeLabel: "" },
  { countryCallingCode: "+234", label: "Nigeria", nativeLabel: "" },
  { countryCallingCode: "+47", label: "Norway", nativeLabel: "Norge" },
  { countryCallingCode: "+968", label: "Oman", nativeLabel: "عُمان" },
  { countryCallingCode: "+92", label: "Pakistan", nativeLabel: "پاکستان" },
  { countryCallingCode: "+680", label: "Palau", nativeLabel: "" },
  { countryCallingCode: "+970", label: "Palestine", nativeLabel: "فلسطين" },
  { countryCallingCode: "+507", label: "Panama", nativeLabel: "Panamá" },
  {
    countryCallingCode: "+675",
    label: "Papua New Guinea",
    nativeLabel: "",
  },
  { countryCallingCode: "+595", label: "Paraguay", nativeLabel: "" },
  { countryCallingCode: "+51", label: "Peru", nativeLabel: "Perú" },
  { countryCallingCode: "+63", label: "Philippines", nativeLabel: "Pilipinas" },
  { countryCallingCode: "+48", label: "Poland", nativeLabel: "Polska" },
  { countryCallingCode: "+351", label: "Portugal", nativeLabel: "Portugal" },
  { countryCallingCode: "+974", label: "Qatar", nativeLabel: "قطر" },
  { countryCallingCode: "+40", label: "Romania", nativeLabel: "România" },
  { countryCallingCode: "+7", label: "Russia", nativeLabel: "Россия" },
  { countryCallingCode: "+250", label: "Rwanda", nativeLabel: "Rwanda" },
  {
    countryCallingCode: "+1 869",
    label: "Saint Kitts and Nevis",
    nativeLabel: "",
  },
  {
    countryCallingCode: "+1 758",
    label: "Saint Lucia",
    nativeLabel: "",
  },
  {
    countryCallingCode: "+1 784",
    label: "Saint Vincent and the Grenadines",
    nativeLabel: "",
  },
  { countryCallingCode: "+685", label: "Samoa", nativeLabel: "" },
  {
    countryCallingCode: "+378",
    label: "San Marino",
    nativeLabel: "San Marino",
  },
  {
    countryCallingCode: "+239",
    label: "Sao Tome and Principe",
    nativeLabel: "São Tomé e Príncipe",
  },
  {
    countryCallingCode: "+966",
    label: "Saudi Arabia",
    nativeLabel: "المملكة العربية السعودية",
  },
  { countryCallingCode: "+221", label: "Senegal", nativeLabel: "Sénégal" },
  { countryCallingCode: "+381", label: "Serbia", nativeLabel: "Србија" },
  {
    countryCallingCode: "+248",
    label: "Seychelles",
    nativeLabel: "",
  },
  {
    countryCallingCode: "+232",
    label: "Sierra Leone",
    nativeLabel: "Sierra Leone",
  },
  { countryCallingCode: "+65", label: "Singapore", nativeLabel: "" },
  { countryCallingCode: "+421", label: "Slovakia", nativeLabel: "Slovensko" },
  { countryCallingCode: "+386", label: "Slovenia", nativeLabel: "Slovenija" },
  {
    countryCallingCode: "+677",
    label: "Solomon Islands",
    nativeLabel: "",
  },
  { countryCallingCode: "+252", label: "Somalia", nativeLabel: "Soomaaliya" },
  {
    countryCallingCode: "+27",
    label: "South Africa",
    nativeLabel: "",
  },
  { countryCallingCode: "+82", label: "South Korea", nativeLabel: "대한민국" },
  {
    countryCallingCode: "+211",
    label: "South Sudan",
    nativeLabel: "",
  },
  { countryCallingCode: "+34", label: "Spain", nativeLabel: "" },
  { countryCallingCode: "+94", label: "Sri Lanka", nativeLabel: "ශ්‍රී ලංකාව" },
  { countryCallingCode: "+249", label: "Sudan", nativeLabel: "السودان" },
  { countryCallingCode: "+597", label: "Suriname", nativeLabel: "Suriname" },
  { countryCallingCode: "+268", label: "Swaziland", nativeLabel: "Swaziland" },
  { countryCallingCode: "+46", label: "Sweden", nativeLabel: "Sverige" },
  { countryCallingCode: "+41", label: "Switzerland", nativeLabel: "Schweiz" },
  { countryCallingCode: "+963", label: "Syria", nativeLabel: "سوريا" },
  { countryCallingCode: "+886", label: "Taiwan", nativeLabel: "台灣" },
  {
    countryCallingCode: "+992",
    label: "Tajikistan",
    nativeLabel: "Тоҷикистон",
  },
  { countryCallingCode: "+255", label: "Tanzania", nativeLabel: "" },
  { countryCallingCode: "+66", label: "Thailand", nativeLabel: "ประเทศไทย" },
  {
    countryCallingCode: "+670",
    label: "Timor-Leste",
    nativeLabel: "Timor-Leste",
  },
  { countryCallingCode: "+228", label: "Togo", nativeLabel: "" },
  { countryCallingCode: "+676", label: "Tonga", nativeLabel: "" },
  {
    countryCallingCode: "+1 868",
    label: "Trinidad and Tobago",
    nativeLabel: "",
  },
  { countryCallingCode: "+216", label: "Tunisia", nativeLabel: "تونس" },
  { countryCallingCode: "+90", label: "Turkey", nativeLabel: "Türkiye" },
  {
    countryCallingCode: "+993",
    label: "Turkmenistan",
    nativeLabel: "Türkmenistan",
  },
  { countryCallingCode: "+688", label: "Tuvalu", nativeLabel: "" },
  { countryCallingCode: "+256", label: "Uganda", nativeLabel: "" },
  { countryCallingCode: "+380", label: "Ukraine", nativeLabel: "Україна" },
  {
    countryCallingCode: "+971",
    label: "United Arab Emirates",
    nativeLabel: "الإمارات العربية المتحدة",
  },
  { countryCallingCode: "+44", label: "United Kingdom", nativeLabel: "" },
  { countryCallingCode: "+1", label: "United States", nativeLabel: "" },
  { countryCallingCode: "+598", label: "Uruguay", nativeLabel: "" },
  {
    countryCallingCode: "+998",
    label: "Uzbekistan",
    nativeLabel: "Oʻzbekiston",
  },
  { countryCallingCode: "+678", label: "Vanuatu", nativeLabel: "" },
  {
    countryCallingCode: "+379",
    label: "Vatican City",
    nativeLabel: "Vaticano",
  },
  { countryCallingCode: "+58", label: "Venezuela", nativeLabel: "" },
  { countryCallingCode: "+84", label: "Vietnam", nativeLabel: "Việt Nam" },
  { countryCallingCode: "+967", label: "Yemen", nativeLabel: "اليمن" },
  { countryCallingCode: "+260", label: "Zambia", nativeLabel: "Zambia" },
  { countryCallingCode: "+263", label: "Zimbabwe", nativeLabel: "" },
];
