export const HangfireJobType = {
  UNSPECIFIED: "UNSPECIFIED",
  ANNUAL_REPORT_ITEMS: "ANNUAL_REPORT_ITEMS",
  DOWNLOAD_MASTER_DATA: "DOWNLOAD_MASTER_DATA",
  DOWNLOAD_OUTBOUND_DELIVERIES: "DOWNLOAD_OUTBOUND_DELIVERIES",
  UPLOAD_MATERIAL_BIN_ASSIGNMENTS: "UPLOAD_MATERIAL_BIN_ASSIGNMENTS",
  DOWNLOAD_TRANSFER_ORDERS: "DOWNLOAD_TRANSFER_ORDERS",
  DEMO_SYSTEM_CLEANER: "DEMO_SYSTEM_CLEANER",
  CLOSE_OUTBOUND_DELIVERIES: "CLOSE_OUTBOUND_DELIVERIES",
  CLOSE_INBOUND_DELIVERIES: "CLOSE_INBOUND_DELIVERIES",
  CLOSE_REBOOKING_DOCUMENTS: "CLOSE_REBOOKING_DOCUMENTS",
  BOOKING_STOCK_OUT: "BOOKING_STOCK_OUT",
  ARCHIVE_ORDERS: "ARCHIVE_ORDERS",
  DELETE_REPLENISHMENT_RUNS: "DELETE_REPLENISHMENT_RUNS",
  DELETE_ARCHIVED_ORDERS: "DELETE_ARCHIVED_ORDERS",
  DELETE_PICK_DELIVERY_PROTOCOLS: "DELETE_PICK_DELIVERY_PROTOCOLS",
  EXTRACTOR_GET_NEXT_UPDATE: "EXTRACTOR_GET_NEXT_UPDATE",
  SAP_PBV_ORDERS: "SAP_PBV_ORDERS",
  DELETE_EMPTY_BINS_IN_AREA: "DELETE_EMPTY_BINS_IN_AREA",
  DELETE_AUDIT_TRAIL: "DELETE_AUDIT_TRAIL",
  DELETE_HANGFIRE_JOB_ASSIGNMENTS: "DELETE_HANGFIRE_JOB_ASSIGNMENTS",
  DELETE_PRINT_JOBS: "DELETE_PRINT_JOBS",
  DELETE_EMPTY_HUS_IN_AREA: "DELETE_EMPTY_HUS_IN_AREA",
  COMPARE_STOCKS: "COMPARE_STOCKS",
  CYCLE_COUNT: "CYCLE_COUNT",
  UPLOAD_MATERIALS: "UPLOAD_MATERIALS",
  VAS_ORDER_CREATION: "VAS_ORDER_CREATION",
  WISAG_STOCK_EXCEL: "WISAG_STOCK_EXCEL",
  APPROVE_CMS_ORDERS: "APPROVE_CMS_ORDERS",
  DELETE_REORDER_RUNS: "DELETE_REORDER_RUNS",
  CLOSE_TRANSFER_DOCUMENTS: "CLOSE_TRANSFER_DOCUMENTS",
  GENERATE_TRANSFER_DOCUMENT_SUGGESTIONS:
    "GENERATE_TRANSFER_DOCUMENT_SUGGESTIONS",
  DELETE_EVENTS: "DELETE_EVENTS",
  CLOSE_COMPLAINT: "CLOSE_COMPLAINT",
  HANDLING_UNIT_TYPE_SI_BASE_CONVERSION:
    "HANDLING_UNIT_TYPE_SI_BASE_CONVERSION",
} as const;

/* eslint-disable @typescript-eslint/no-redeclare */
export type HangfireJobType =
  typeof HangfireJobType[keyof typeof HangfireJobType];
/* eslint-enable */
