export const LinkedDeliveryTypeEnum = {
  INBOUND_DELIVERY: "INBOUND_DELIVERY",
  OUTBOUND_DELIVERY: "OUTBOUND_DELIVERY",
  INBOUND_DELIVERY_ITEM: "INBOUND_DELIVERY_ITEM",
  OUTBOUND_DELIVERY_ITEM: "OUTBOUND_DELIVERY_ITEM",
} as const;
